---

codecov:
  notify:
    after_n_builds: 24  # The number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: bb0fa8d8-1f5b-4b59-95f4-ec338cbd13a4  # repo-scoped

comment:
  require_changes: true

coverage:
  range: 99.34..100
  status:
    patch:
      default:
        target: 100%
        flags:
        - pytest
    project:
      default:
        target: 85%  # 100%
      lib:
        flags:
        - pytest
        paths:
        - propcache/
        target: 100%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 97.87%  # 100%
      typing:
        flags:
        - MyPy
        target: 70%  # 100%

...
